### ISSUE TITLE
Method 'initialize()'将被弃用

### ISSUE THREAD

**Issue by LukiWen** [netyouli/WHC_Layout#1]
Method 'initialize()' defines Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions   大神能把这个问题给解决下吗？没找到解决方法

**Comment by netyouli** [comment]
shi de 最新版本已经除去initialize这个方法，如果要使用自动计算高度，请在appdelegate里面调用UITableView.whc_InitConfig()即可
